/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as appEmployeeIndexRouteImport } from './routes/(app)/employee/index'
import { Route as appDepartmentIndexRouteImport } from './routes/(app)/department/index'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const appEmployeeIndexRoute = appEmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDepartmentIndexRoute = appDepartmentIndexRouteImport.update({
  id: '/department/',
  path: '/department/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/department/': typeof appDepartmentIndexRoute
  '/employee/': typeof appEmployeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/department': typeof appDepartmentIndexRoute
  '/employee': typeof appEmployeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/department/': typeof appDepartmentIndexRoute
  '/(app)/employee/': typeof appEmployeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/dashboard/' | '/department/' | '/employee/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/dashboard' | '/department' | '/employee'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)/sign-in'
    | '/(app)/dashboard/'
    | '/(app)/department/'
    | '/(app)/employee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/employee/': {
      id: '/(app)/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof appEmployeeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/department/': {
      id: '/(app)/department/'
      path: '/department'
      fullPath: '/department/'
      preLoaderRoute: typeof appDepartmentIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appDepartmentIndexRoute: typeof appDepartmentIndexRoute
  appEmployeeIndexRoute: typeof appEmployeeIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardIndexRoute: appDashboardIndexRoute,
  appDepartmentIndexRoute: appDepartmentIndexRoute,
  appEmployeeIndexRoute: appEmployeeIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
